name: Deploy to AWS S3 on push to main branch

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deployToAWSS3:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: brockneedscoffee/s3-docusaurus-sync-action@master
        env:
          AWS_DEFAULT_REGION: 'us-west-2'
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
